server:
  port: 9003
spring:
  application:
    name: zuul-api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8899/eureka/,http://localhost:8898/eureka/

zuul:
  routes:
    consumer:                       #规则名称
      path: /consumer/**            #需要拦截的请求
      serviceId: eureka-consumer    #为拦截的请求映射的服务
      sensitiveHeaders:             #传递cookie到这个服务
    hello:
      path: /hello/**
      serviceId: hello-service
  #ignored-patterns: /**/admin/**     #忽略的路径
  #ignored-services:  hello-service  #忽略的服务，不能通过zuul访问
